#!/bin/sh

# -- get the GeoIP2-Java v2.12.0
# and its dependecies
wget https://github.com/maxmind/GeoIP2-java/releases/download/v2.12.0/geoip2-2.12.0-with-dependencies.zip
unzip geoip2-2.12.0-with-dependencies.zip
rm *zip
mkdir ../lib
mv geoip2-2.12.0/lib/* ../lib
rm -Rf geoip2-2.12.0